### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by dmitshur** [gopherjs/webgl#6]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with webgl. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable webgl on @Sourcegraph by going to https://sourcegraph.com/github.com/gopherjs/webgl and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by Konstantin8105** [comment]
Dear @shurcooL , 
Could you add demo in repo.
